# Build options enabling different permutations and exluding unwanted software
# applications
option(FETCH_GSDK "Force CMAKE to fetch Gecko SDK from GitHub" OFF)
option(BUILD_ZIGPC "Package the ZIGPC" OFF)
option(BUILD_ZPC "Package the ZPC" ON)
option(BUILD_DEV_GUI "Package the developer GUI" OFF)
option(BUILD_UIC_DEMO "Package the Unify demo" ON)
option(BUILD_UPVL "Package the UIC-UPVL" ON)
option(BUILD_GMS "Package the UIC-GMS" ON)
option(BUILD_IMAGE_PROVIDER "Build the UIC-IMAGE-PROVIDER" ON)
option(BUILD_AOXPC "Package the AOXPC" OFF)
option(BUILD_POSITIONING "Package the Positioning Service" OFF)
option(BUILD_NAL "Package the Name and location service" ON)
option(BUILD_UPTI_CAP "Build the UIC-UPTI-CAP" ON)
option(BUILD_UPTI_WRITER "Build the UIC-UPTI-WRITER" ON)
option(BUILD_CPCD "Package CPCd" OFF)
option(BUILD_ZIGBEED "Build Zigbeed" OFF)
option(BUILD_OTBR "Build OpenThread Border Router" OFF)
option(BUILD_MATTER_BRIDGE "Build the Matter Bridge" OFF)
option(BUILD_EPC "Build EPC (Example Protocol Controller)" ON)
option(BUILD_EMD "Build EMD (Example MQTT Device)" OFF)
